export const styles = {
  button: {
    width: 'auto',
    textTransform: 'capitalize',
    fontSize: '14px',
  },
}

export const columns = [
  {
    key: 'selection-cell',
    style: { width: 60 },
    visible: true,
  },
  {
    key: 'formatted_created_at',
    title: 'Created At',
    dataType: 'date',
    style: { width: 250 },
    visible: true,
  },
  {
    key: 'id',
    title: 'IO No',
    dataType: 'string',
    style: { width: 100 },
    visible: true,
  },
  {
    key: 'io_for',
    title: 'IO For',
    dataType: 'string',
    style: { width: 150 },
    visible: true,
  },
  {
    key: 'campaign',
    title: 'Campaign',
    dataType: 'string',
    style: { width: 250 },
    visible: true,
  },
  {
    key: 'customer',
    title: 'Customer',
    dataType: 'string',
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'affiliate',
    title: 'Affiliate',
    dataType: 'string',
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'phone',
    title: 'Phone',
    dataType: 'string',
    style: { width: 150 },
    visible: true,
  },
  {
    key: 'term',
    title: 'Term',
    dataType: 'string',
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'call_length',
    title: 'Call Length (Sec.)',
    dataType: 'string',
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'payout',
    title: 'Payout',
    dataType: 'string',
    style: { width: 100 },
    visible: true,
  },
  {
    key: 'revenue',
    title: 'Revenue',
    dataType: 'string',
    style: { width: 100 },
    visible: true,
  },
  {
    key: 'status',
    title: 'Status',
    dataType: 'string',
    style: { width: 100 },
    visible: true,
  },
  {
    key: 'io_link',
    title: 'IO Public Link',
    dataType: 'string',
    style: { width: 150 },
    visible: true,
  },
  {
    key: 'resend_io_doc',
    title: 'Resend IO DOC',
    style: { width: 150 },
    visible: true,
  },
  {
    key: 'cancel_io',
    title: 'Cancel IO',
    style: { width: 120 },
    visible: true,
  },
]
