export const buttonStyle = {
  width: 'auto',
  textTransform: 'capitalize',
  fontSize: '14px',
}

export const columns = [
  {
    key: 'selection-cell',
    style: { width: 80 },
    visible: true,
  },
  {
    key: 'sl',
    title: 'SL',
    dataType: 'number',
    style: { width: 100 },
    visible: false,
  },
  {
    key: 'SN',
    title: 'SN',
    dataType: 'string',
    style: { width: 130 },
    visible: true,
  },
  {
    key: 'Call_Date_Time',
    title: 'Call Time (EST)',
    dataType: 'date',
    style: { width: 230 },
    visible: true,
  },

  {
    key: 'Inbound_Id',
    title: 'Inbound Id',
    dataType: 'string',
    style: { width: 500 },
    visible: true,
  },
  {
    key: 'Affiliate',
    title: 'Affiliate',
    dataType: 'string',
    style: { width: 240 },
    visible: true,
  },
  {
    key: 'Market',
    title: 'Market',
    dataType: 'string',
    style: { width: 350 },
    visible: true,
  },
  {
    key: 'Campaign',
    title: 'Campaign',
    dataType: 'string',
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'Inbound',
    title: 'Inbound',
    dataType: 'string',
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'Dialed',
    title: 'Dialed',
    dataType: 'string',
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'Type',
    title: 'Type',
    dataType: 'string',
    style: { width: 100 },
    visible: true,
  },
  {
    key: 'Customer',
    title: 'Customer',
    dataType: 'string',
    style: { width: 240 },
    visible: true,
  },
  {
    key: 'Target',
    title: 'Target',
    dataType: 'string',
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'Target_Number',
    title: 'Target Number',
    dataType: 'string',
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'Target_Description',
    title: 'Target Description',
    dataType: 'string',
    style: { width: 300 },
    visible: true,
  },
  {
    key: 'Call_Length_In_Seconds',
    title: 'Call Length In Seconds',
    dataType: 'number',
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'Revenue',
    title: 'Revenue',
    dataType: 'number',
    style: { width: 120 },
    visible: true,
  },
  {
    key: 'Conn_Duration',
    title: 'Conn.Duration',
    dataType: 'number',
    style: { width: 150 },
    visible: true,
  },
  {
    key: 'Payout',
    title: 'Payout',
    dataType: 'number',
    style: { width: 100 },
    visible: true,
  },
  {
    key: 'Total_Cost',
    title: 'Total Cost',
    dataType: 'number',
    style: { width: 120 },
    visible: true,
  },
  {
    key: 'Profit',
    title: 'Profit',
    dataType: 'number',
    style: { width: 120 },
    visible: true,
  },
  {
    key: 'City',
    title: 'City',
    dataType: 'string',
    style: { width: 150 },
    visible: true,
  },
  {
    key: 'State',
    title: 'State',
    dataType: 'string',
    style: { width: 120 },
    visible: true,
  },
  {
    key: 'Zipcode',
    title: 'Zipcode',
    dataType: 'string',
    style: { width: 120 },
    visible: true,
  },
]
