import { DataType } from "ka-table/enums";

export const columns = [
  {
    key: 'edit',
    style: { width: 10 },
    visible: false,
  },
  {
    key: 'selection-cell',
    style: { width: 80 },
    visible: true,
  },
  {
    key: 'sl',
    title: 'SL',
    dataType: DataType.Number,
    style: { width: 100 },
    visible: false,
  },
  {
    key: 'SN',
    title: 'SN',
    dataType: DataType.String,
    style: { width: 130 },
    visible: true,
  },
  {
    key: 'Call_Date_Time',
    title: 'Call Time (EST)',
    dataType: DataType.Date,
    style: { width: 230 },
    visible: true,
  },

  {
    key: 'Has_Annotation',
    title: 'Has Annotation',
    dataType: DataType.String,
    style: { width: 160 },
    visible: true,
  },
  {
    key: 'Annotation_Tag',
    title: 'Annotation Tag',
    dataType: DataType.String,
    style: { width: 350 },
    visible: true,
  },
  {
    key: 'Call_Status',
    title: 'Call Status',
    dataType: DataType.String,
    style: { width: 130 },
    visible: true,
  },
  {
    key: 'Duplicate_Call',
    title: 'Duplicate Call',
    dataType: DataType.String,
    style: { width: 150 },
    visible: true,
  },
  {
    key: 'Recording_Url',
    title: 'Recording_Url',
    dataType: DataType.String,
    style: { width: 360 },
    visible: true,
  },
  {
    key: 'Inbound_Id',
    title: 'Inbound Id',
    dataType: DataType.String,
    style: { width: 600 },
    visible: true,
  },
  {
    key: 'Affiliate',
    title: 'Affiliate',
    dataType: DataType.String,
    style: { width: 240 },
    visible: true,
  },
  {
    key: 'Market',
    title: 'Market',
    dataType: DataType.String,
    style: { width: 350 },
    visible: true,
  },
  {
    key: 'Campaign',
    title: 'Campaign',
    dataType: DataType.String,
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'Inbound',
    title: 'Inbound',
    dataType: DataType.String,
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'Dialed',
    title: 'Dialed',
    dataType: DataType.String,
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'Type',
    title: 'Type',
    dataType: DataType.String,
    style: { width: 100 },
    visible: true,
  },
  {
    key: 'Customer',
    title: 'Customer',
    dataType: DataType.String,
    style: { width: 240 },
    visible: true,
  },
  {
    key: 'Target',
    title: 'Target',
    dataType: DataType.String,
    style: { width: 350 },
    visible: true,
  },
  {
    key: 'Target_Number',
    title: 'Target Number',
    dataType: DataType.String,
    style: { width: 200 },
    visible: true,
  },
  {
    key: 'Target_Description',
    title: 'Target Description',
    dataType: DataType.String,
    style: { width: 400 },
    visible: true,
  },
  {
    key: 'Source_Hangup',
    title: 'Source/Hangup',
    dataType: DataType.String,
    style: { width: 240 },
    visible: true,
  },
  {
    key: 'Time_To_Call',
    title: 'Time To Call',
    dataType: DataType.Number,
    style: { width: 130 },
    visible: true,
  },
  {
    key: 'call_Length_In_Seconds',
    title: 'Call Length In Seconds',
    dataType: DataType.Number,
    style: { width: 240 },
    visible: true,
  },
  {
    key: 'Revenue',
    title: 'Revenue',
    dataType: DataType.Number,
    style: { width: 120 },
    visible: true,
  },
  {
    key: 'Conn_Duration',
    title: 'Conn.Duration',
    dataType: DataType.Number,
    style: { width: 240 },
    visible: true,
  },
  {
    key: 'payoutAmount',
    title: 'Payout',
    dataType: DataType.Number,
    style: { width: 100 },
    visible: true,
  },
  {
    key: 'Total_Cost',
    title: 'Total Cost',
    dataType: DataType.Number,
    style: { width: 120 },
    visible: true,
  },
  {
    key: 'Profit',
    title: 'Profit',
    dataType: DataType.Number,
    style: { width: 120 },
    visible: true,
  },
  {
    key: 'City',
    title: 'City',
    dataType: DataType.String,
    style: { width: 240 },
    visible: true,
  },
  {
    key: 'State',
    title: 'State',
    dataType: DataType.String,
    style: { width: 240 },
    visible: true,
  },
  {
    key: 'Zipcode',
    title: 'Zipcode',
    dataType: DataType.String,
    style: { width: 240 },
    visible: true,
  },
]
